tab_spaces = 2

# max line length (default 100)
max_width = 120

# [unstable] Wrap long lines using 2-space indentation
# indent_style = "Block"

# [unstable] hex/binary formatting
# hex_literal_case = "Upper"
